name: push

env:
  COMMIT_ID: ${{ github.sha::7 }}
  VERSION: ${{ github.head_ref }}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-id
        run: |
          echo ${COMMIT_ID}
          echo ${VERSION}
