name: push

env:
  COMMIT_ID: ${{ github.sha }}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: commit-id
        env:
          COMMIT_SHORT_ID: ${GITHUB_SHA::7}
        run: |
          echo ${COMMIT_ID}
          echo ${COMMIT_SHORT_ID}
          echo ${GITHUB_SHA::7}
