name: release

env:
  RELEASE_REF: ${{ github.ref }}

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set ENV
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          
      - name: version
        run: | 
          echo ${RELEASE_REF}
          echo ${RELEASE_TAG}
          echo ${RELEASE_BRANCH}