name: release

env:
  RELEASE_REF: ${{ github.ref }}

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: version 
        env:
          RELEASE_TAG: ${GITHUB_REF#refs/*/}
        run: | 
          echo ${RELEASE_REF}
          echo ${RELEASE_TAG}